# rtemsmbuf-e10.py — find the libbsd mbuf-cluster ceiling on armv7-rtems, and
# find out what the IOC does when it is reached.
#
# Why this is a separate arena from everything already measured: the IOC's heap
# query (`RTEMS:MEM_FREE` / `MEM_BLK`, i.e. `_Protected_heap_Get_information`
# over `RTEMS_Malloc_Heap`, i.e. `malloc_free_space()`) cannot see mbuf clusters
# at all.  libbsd takes its packet memory from its own allocator domain, sized
# by `RTEMS_BSD_ALLOCATOR_DOMAIN_PAGE_MBUF_DEFAULT` = 8 MiB
# (`rtemsbsd/include/rtems/bsd/bsd.h:59`), and `kern_mbuf.c:146` then sets
#
#     nmbclusters = maxmbufmem / MCLBYTES / 4 = 8388608 / 2048 / 4 = 1024
#
# `crates/epics-rtems-boot/csrc/rtems_init.c:264` calls `rtems_bsd_initialize()`
# without touching `rtems_bsd_allocator_domain_page_mbuf_size`, so the default
# stands.  1024 clusters is the whole packet budget for the target; this arm is
# the behavioural check on that number and on what happens at it.
#
# Method.  Every load client subscribes and then never reads its socket, so the
# server's writes back up into that socket's send buffer, which is where the
# clusters go.  The events are generated by a client this script controls — a
# dedicated writer looping CA_PROTO_WRITE on a passive PV — rather than by the
# guest's own 5 Hz tick task, because that task runs at `ThreadPriority::Low`
# and stops being scheduled under exactly this load.
#
# The ceiling is then found by threshold search on the client count across fresh
# boots: `[zone: mbuf_cluster] kern.ipc.nmbclusters limit reached` on the guest
# console is the marker.  Liveness afterwards is what decides whether this is a
# third budgeted resource or a new defect.
import select
import socket
import struct
import sys
import time

HOST, PORT = "127.0.0.1", 25164
NCLIENT = int(sys.argv[1]) if len(sys.argv) > 1 else 32
NSUB = int(sys.argv[2]) if len(sys.argv) > 2 else 100
BLAST_SECS = float(sys.argv[3]) if len(sys.argv) > 3 else 25.0
HOLD = float(sys.argv[4]) if len(sys.argv) > 4 else 40.0
TAG = sys.argv[5] if len(sys.argv) > 5 else "mbuf"

PV = "RTEMS:AO"
MONPV = ("RTEMS:UPTIME", "RTEMS:MEM_FREE", "RTEMS:MEM_BLK", "RTEMS:CA_CONN_CNT",
         "RTEMS:CA_REFUSED_CNT")
T0 = time.time()


def log(m):
    print("[%7.1fs] %s %s" % (time.time() - T0, TAG, m), flush=True)


def hdr(cmd, psize, dtype, dcount, p1, p2):
    return struct.pack(">HHHHII", cmd, psize, dtype, dcount, p1, p2)


def pad(s):
    b = s.encode() + b"\0"
    return b.ljust((len(b) + 7) // 8 * 8, b"\0")


def msgs(buf):
    out = []
    while len(buf) >= 16:
        cmd, psize, dt, dc, p1, p2 = struct.unpack(">HHHHII", buf[:16])
        if len(buf) < 16 + psize:
            break
        out.append((cmd, psize, dt, dc, p1, p2, buf[16:16 + psize]))
        buf = buf[16 + psize:]
    return out, buf


def decode(dt, pl):
    if dt == 6 and len(pl) >= 8:
        return struct.unpack(">d", pl[:8])[0]
    if dt == 5 and len(pl) >= 4:
        return struct.unpack(">i", pl[:4])[0]
    if dt == 0:
        return pl.split(b"\0")[0].decode("latin1")
    return pl[:16]


class Sess:
    def __init__(self, idx, timeout=25):
        self.idx = idx
        self.s = socket.create_connection((HOST, PORT), timeout=timeout)
        self.s.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
        self.buf = b""
        self.ch = {}
        self.errors = []
        self.s.sendall(hdr(0, 0, 0, 13, 0, 0))

    def drain(self, budget=0.25, until=None):
        end = time.time() + budget
        got = 0
        while True:
            if until is not None and until(self):
                break
            left = end - time.time()
            if left <= 0:
                break
            r, _, _ = select.select([self.s], [], [], min(0.05, left))
            if not r:
                continue
            c = self.s.recv(262144)
            if not c:
                raise RuntimeError("EOF")
            got += len(c)
            self.buf += c
            ms, self.buf = msgs(self.buf)
            for (cmd, _ps, dt, dc, p1, p2, pl) in ms:
                if cmd == 18:
                    self.ch[p1] = (p2, dt, dc)
                elif cmd == 11:
                    self.errors.append((p2, pl[16:].split(b"\0")[0].decode("latin1")))
        return got

    def create(self, pv, cid, budget=25.0):
        nm = pad(pv)
        self.s.sendall(hdr(18, len(nm), 0, 0, cid, 13) + nm)
        self.drain(budget, until=lambda s: cid in s.ch)
        return cid in self.ch

    def subscribe(self, cid, n):
        sid, dt, dc = self.ch[cid]
        mask = struct.pack(">fffHH", 0.0, 0.0, 0.0, 1, 0)
        self.s.sendall(b"".join(
            hdr(1, 16, dt, dc, sid, cid * 4096 + k) + mask for k in range(n)))

    def write(self, cid, value):
        sid, dt, dc = self.ch[cid]
        pl = struct.pack(">d", value)
        self.s.sendall(hdr(4, len(pl), 6, 1, sid, 0) + pl)


smp = Sess(9000)
smp_cid = {}
for pv in MONPV:
    cid = 800 + len(smp_cid)
    nm = pad(pv)
    smp.s.sendall(hdr(18, len(nm), 0, 0, cid, 13) + nm)
    smp_cid[pv] = cid
smp.drain(40.0, until=lambda s: len(s.ch) >= len(MONPV))
_ioid = [6000]


def read_one(pv, timeout=20):
    cid = smp_cid[pv]
    if cid not in smp.ch:
        return "NOCHAN"
    sid, dt, dc = smp.ch[cid]
    _ioid[0] += 1
    ioid = _ioid[0]
    smp.s.sendall(hdr(15, 0, dt, dc, sid, ioid))
    end = time.time() + timeout
    while time.time() < end:
        smp.s.settimeout(max(0.05, end - time.time()))
        try:
            c = smp.s.recv(65536)
        except socket.timeout:
            return "TIMEOUT"
        if not c:
            raise RuntimeError("EOF")
        smp.buf += c
        ms, smp.buf = msgs(smp.buf)
        for (cmd, _ps, t, _dc, p1, p2, pl) in ms:
            if cmd == 18:
                smp.ch[p1] = (p2, t, _dc)
            elif cmd == 15 and p2 == ioid:
                return decode(t, pl)
    return "TIMEOUT"


def sample(tag):
    v = {}
    for pv in MONPV:
        try:
            v[pv] = read_one(pv)
        except Exception as e:
            v[pv] = "ERR:%r" % e
    log("SAMPLE %-12s up=%s MEM_FREE=%s MEM_BLK=%s CONN=%s REFUSED=%s"
        % (tag, v.get("RTEMS:UPTIME"), v.get("RTEMS:MEM_FREE"),
           v.get("RTEMS:MEM_BLK"), v.get("RTEMS:CA_CONN_CNT"),
           v.get("RTEMS:CA_REFUSED_CNT")))
    return v


def liveness(tag):
    """A fresh, well-behaved client: connect, create, read.  This is the whole
    question — an IOC that refuses politely still answers here."""
    t = time.time()
    try:
        c = Sess(50000, timeout=25)
        ok = c.create(PV, 61, budget=20.0)
        val = None
        if ok:
            sid, dt, dc = c.ch[61]
            c.s.sendall(hdr(15, 0, dt, dc, sid, 6100))
            end = time.time() + 20
            while time.time() < end and val is None:
                c.drain(1.0)
                ms, _ = msgs(b"")
                val = "read-issued"
        log("LIVENESS %-10s connect+create=%s errors=%r in %.1fs"
            % (tag, ok, c.errors[:1], time.time() - t))
        c.s.close()
        return ok
    except Exception as e:
        log("LIVENESS %-10s FAILED after %.1fs: %r" % (tag, time.time() - t, e))
        return False


log("clients=%d subs/client=%d blast=%.0fs hold=%.0fs  "
    "(source predicts nmbclusters=1024 from an 8 MiB mbuf domain)"
    % (NCLIENT, NSUB, BLAST_SECS, HOLD))
sample("idle")
liveness("before")

loads = []
for i in range(NCLIENT):
    try:
        c = Sess(i)
        if not c.create(PV, 10):
            log("client %d got no channel; stopping the ramp" % i)
            break
        # NSUB=0 skips subscriptions entirely.  It has to be possible to skip
        # them: `record_instance` caps subscribers per record FIELD at 1024, and
        # every refused EVENT_ADD past that prints two WARN lines to the serial
        # console.  A first version of this arm subscribed 3,200 times to one
        # field and produced 4,346 console lines, which is its own load and
        # confounds what the blast is being blamed for.
        if NSUB:
            c.subscribe(10, NSUB)
        loads.append(c)
    except Exception as e:
        log("client %d FAILED: %r" % (i, e))
        break
log("connected %d non-reading subscribers, %d subscriptions total"
    % (len(loads), len(loads) * NSUB))

# Monitor traffic alone does not reach the cluster ceiling: a CA monitor frame
# is ~48 B, below FreeBSD's `MINCLSIZE`, so it is carried in plain 256 B mbufs
# from `zone_mbuf` and never touches `zone_clust`.  Measured — 96 non-reading
# subscribers with 9,600 subscriptions and 300 writes produced zero
# `nmbclusters limit reached` lines.
#
# Clusters are consumed by INBOUND full-size TCP segments.  So the load that
# reaches the ceiling is the one the failed first arm accidentally created:
# clients that keep sending while refusing to read, so the server's writes block
# its per-client thread, that thread stops reading, and inbound data piles up in
# the receive socket buffer in 1460 B segments.
blasted = [0] * len(loads)
for c in loads:
    c.s.setblocking(False)
end = time.time() + BLAST_SECS
rounds = 0
while time.time() < end:
    rounds += 1
    progressed = False
    for i, c in enumerate(loads):
        sid, dt, dc = c.ch[10]
        pkt = b"".join(hdr(15, 0, dt, dc, sid, 7000 + k) for k in range(256))
        try:
            n = c.s.send(pkt)
            blasted[i] += n
            progressed = True
        except (BlockingIOError, InterruptedError):
            continue
        except OSError:
            continue
    if not progressed:
        time.sleep(0.05)
for c in loads:
    try:
        c.s.setblocking(True)
    except OSError:
        pass
log("blast: %d rounds, %d B pushed to the guest, min/max per client %d/%d"
    % (rounds, sum(blasted), min(blasted) if blasted else 0,
       max(blasted) if blasted else 0))

time.sleep(HOLD)
sample("loaded")
alive = liveness("under-load")

for c in loads:
    try:
        c.s.close()
    except Exception:
        pass
try:
    wr.s.close()
except Exception:
    pass
log("released %d load clients; settling 30 s" % len(loads))
time.sleep(30)
sample("released")
recovered = liveness("after")
log("rtemsmbuf done: under_load=%s recovered=%s" % (alive, recovered))
