//! EPICS environment parameters — the Rust `envData.c`.
//!
//! @generated by `cargo run -p env-codegen -- --write` from the vendored
//! `crates/epics-base-rs/envconfig/{envDefs.h,CONFIG_ENV,CONFIG_SITE_ENV}`.
//! DO NOT EDIT — edit the spec and regenerate. `env-codegen --check` fails on
//! drift and runs as part of `cargo nextest run -p env-codegen`.
//!
//! This module is the workspace's ONLY declaration of an EPICS environment
//! default. [`EnvParam`](super::env::EnvParam) cannot be constructed outside
//! `epics-libcom-rs`, and none of its accessors take a `default` argument, so a
//! caller has no way to introduce a second one.

use super::build_info;
use super::env::EnvParam;

/// Compiled default: empty, so `get()` answers `None` (C `envGetConfigParamPtr`).
pub const EPICS_CA_ADDR_LIST: EnvParam = EnvParam::new("EPICS_CA_ADDR_LIST", "");
/// Compiled default: `"30.0"`.
pub const EPICS_CA_CONN_TMO: EnvParam = EnvParam::new("EPICS_CA_CONN_TMO", "30.0");
/// Compiled default: `"YES"`.
pub const EPICS_CA_AUTO_ADDR_LIST: EnvParam = EnvParam::new("EPICS_CA_AUTO_ADDR_LIST", "YES");
/// Compiled default: `"5065"`.
pub const EPICS_CA_REPEATER_PORT: EnvParam = EnvParam::new("EPICS_CA_REPEATER_PORT", "5065");
/// Compiled default: `"5064"`.
pub const EPICS_CA_SERVER_PORT: EnvParam = EnvParam::new("EPICS_CA_SERVER_PORT", "5064");
/// Compiled default: `"16384"`.
pub const EPICS_CA_MAX_ARRAY_BYTES: EnvParam = EnvParam::new("EPICS_CA_MAX_ARRAY_BYTES", "16384");
/// Compiled default: `"YES"`.
pub const EPICS_CA_AUTO_ARRAY_BYTES: EnvParam = EnvParam::new("EPICS_CA_AUTO_ARRAY_BYTES", "YES");
/// Compiled default: `"300.0"`.
pub const EPICS_CA_MAX_SEARCH_PERIOD: EnvParam =
    EnvParam::new("EPICS_CA_MAX_SEARCH_PERIOD", "300.0");
/// Compiled default: empty, so `get()` answers `None` (C `envGetConfigParamPtr`).
pub const EPICS_CA_NAME_SERVERS: EnvParam = EnvParam::new("EPICS_CA_NAME_SERVERS", "");
/// Compiled default: `"1"`.
pub const EPICS_CA_MCAST_TTL: EnvParam = EnvParam::new("EPICS_CA_MCAST_TTL", "1");
/// Compiled default: empty, so `get()` answers `None` (C `envGetConfigParamPtr`).
pub const EPICS_CAS_INTF_ADDR_LIST: EnvParam = EnvParam::new("EPICS_CAS_INTF_ADDR_LIST", "");
/// Compiled default: empty, so `get()` answers `None` (C `envGetConfigParamPtr`).
pub const EPICS_CAS_IGNORE_ADDR_LIST: EnvParam = EnvParam::new("EPICS_CAS_IGNORE_ADDR_LIST", "");
/// Compiled default: empty, so `get()` answers `None` (C `envGetConfigParamPtr`).
pub const EPICS_CAS_AUTO_BEACON_ADDR_LIST: EnvParam =
    EnvParam::new("EPICS_CAS_AUTO_BEACON_ADDR_LIST", "");
/// Compiled default: empty, so `get()` answers `None` (C `envGetConfigParamPtr`).
pub const EPICS_CAS_BEACON_ADDR_LIST: EnvParam = EnvParam::new("EPICS_CAS_BEACON_ADDR_LIST", "");
/// Compiled default: empty, so `get()` answers `None` (C `envGetConfigParamPtr`).
pub const EPICS_CAS_SERVER_PORT: EnvParam = EnvParam::new("EPICS_CAS_SERVER_PORT", "");
/// Compiled default: `"15.0"`.
pub const EPICS_CA_BEACON_PERIOD: EnvParam = EnvParam::new("EPICS_CA_BEACON_PERIOD", "15.0");
/// Compiled default: empty, so `get()` answers `None` (C `envGetConfigParamPtr`).
pub const EPICS_CAS_BEACON_PERIOD: EnvParam = EnvParam::new("EPICS_CAS_BEACON_PERIOD", "");
/// Compiled default: empty, so `get()` answers `None` (C `envGetConfigParamPtr`).
pub const EPICS_CAS_BEACON_PORT: EnvParam = EnvParam::new("EPICS_CAS_BEACON_PORT", "");
/// Compiled default: the build that produced this binary (`build_info::COMPILER_CLASS`).
pub const EPICS_BUILD_COMPILER_CLASS: EnvParam =
    EnvParam::new("EPICS_BUILD_COMPILER_CLASS", build_info::COMPILER_CLASS);
/// Compiled default: the build that produced this binary (`build_info::OS_CLASS`).
pub const EPICS_BUILD_OS_CLASS: EnvParam =
    EnvParam::new("EPICS_BUILD_OS_CLASS", build_info::OS_CLASS);
/// Compiled default: the build that produced this binary (`build_info::TARGET_ARCH`).
pub const EPICS_BUILD_TARGET_ARCH: EnvParam =
    EnvParam::new("EPICS_BUILD_TARGET_ARCH", build_info::TARGET_ARCH);
/// Compiled default: `"CST6CDT,M3.2.0/2,M11.1.0/2"`.
pub const EPICS_TZ: EnvParam = EnvParam::new("EPICS_TZ", "CST6CDT,M3.2.0/2,M11.1.0/2");
/// Compiled default: empty, so `get()` answers `None` (C `envGetConfigParamPtr`).
pub const EPICS_TS_NTP_INET: EnvParam = EnvParam::new("EPICS_TS_NTP_INET", "");
/// Compiled default: empty, so `get()` answers `None` (C `envGetConfigParamPtr`).
pub const EPICS_IOC_IGNORE_SERVERS: EnvParam = EnvParam::new("EPICS_IOC_IGNORE_SERVERS", "");
/// Compiled default: `"7004"`.
pub const EPICS_IOC_LOG_PORT: EnvParam = EnvParam::new("EPICS_IOC_LOG_PORT", "7004");
/// Compiled default: empty, so `get()` answers `None` (C `envGetConfigParamPtr`).
pub const EPICS_IOC_LOG_INET: EnvParam = EnvParam::new("EPICS_IOC_LOG_INET", "");
/// Compiled default: `"1000000"`.
pub const EPICS_IOC_LOG_FILE_LIMIT: EnvParam = EnvParam::new("EPICS_IOC_LOG_FILE_LIMIT", "1000000");
/// Compiled default: empty, so `get()` answers `None` (C `envGetConfigParamPtr`).
pub const EPICS_IOC_LOG_FILE_NAME: EnvParam = EnvParam::new("EPICS_IOC_LOG_FILE_NAME", "");
/// Compiled default: empty, so `get()` answers `None` (C `envGetConfigParamPtr`).
pub const EPICS_IOC_LOG_FILE_COMMAND: EnvParam = EnvParam::new("EPICS_IOC_LOG_FILE_COMMAND", "");
/// Compiled default: `"\u{1b}[32;1mepics> \u{1b}[0m"`.
pub const IOCSH_PS1: EnvParam = EnvParam::new("IOCSH_PS1", "\u{1b}[32;1mepics> \u{1b}[0m");
/// Compiled default: `"50"`.
pub const IOCSH_HISTSIZE: EnvParam = EnvParam::new("IOCSH_HISTSIZE", "50");
/// Compiled default: empty, so `get()` answers `None` (C `envGetConfigParamPtr`).
pub const IOCSH_HISTEDIT_DISABLE: EnvParam = EnvParam::new("IOCSH_HISTEDIT_DISABLE", "");
/// Compiled default: `"NO"`.
pub const EPICS_ABORT_ON_ASSERT: EnvParam = EnvParam::new("EPICS_ABORT_ON_ASSERT", "NO");
/// Compiled default: `"YES"`.
pub const EPICS_ALLOW_POSIX_THREAD_PRIORITY_SCHEDULING: EnvParam =
    EnvParam::new("EPICS_ALLOW_POSIX_THREAD_PRIORITY_SCHEDULING", "YES");

/// C `env_param_list[]` (`envDefs.h:87`) — every parameter EPICS Base knows,
/// in declaration order. `epicsPrtEnvParams` walks exactly this list.
pub const ENV_PARAM_LIST: &[EnvParam] = &[
    EPICS_CA_ADDR_LIST,
    EPICS_CA_CONN_TMO,
    EPICS_CA_AUTO_ADDR_LIST,
    EPICS_CA_REPEATER_PORT,
    EPICS_CA_SERVER_PORT,
    EPICS_CA_MAX_ARRAY_BYTES,
    EPICS_CA_AUTO_ARRAY_BYTES,
    EPICS_CA_MAX_SEARCH_PERIOD,
    EPICS_CA_NAME_SERVERS,
    EPICS_CA_MCAST_TTL,
    EPICS_CAS_INTF_ADDR_LIST,
    EPICS_CAS_IGNORE_ADDR_LIST,
    EPICS_CAS_AUTO_BEACON_ADDR_LIST,
    EPICS_CAS_BEACON_ADDR_LIST,
    EPICS_CAS_SERVER_PORT,
    EPICS_CA_BEACON_PERIOD,
    EPICS_CAS_BEACON_PERIOD,
    EPICS_CAS_BEACON_PORT,
    EPICS_BUILD_COMPILER_CLASS,
    EPICS_BUILD_OS_CLASS,
    EPICS_BUILD_TARGET_ARCH,
    EPICS_TZ,
    EPICS_TS_NTP_INET,
    EPICS_IOC_IGNORE_SERVERS,
    EPICS_IOC_LOG_PORT,
    EPICS_IOC_LOG_INET,
    EPICS_IOC_LOG_FILE_LIMIT,
    EPICS_IOC_LOG_FILE_NAME,
    EPICS_IOC_LOG_FILE_COMMAND,
    IOCSH_PS1,
    IOCSH_HISTSIZE,
    IOCSH_HISTEDIT_DISABLE,
    EPICS_ABORT_ON_ASSERT,
    EPICS_ALLOW_POSIX_THREAD_PRIORITY_SCHEDULING,
];
