//! The EPICS Base release this crate ports — the Rust `epicsVersion.h`.
//!
//! @generated by `cargo run -p env-codegen -- --write` from the vendored
//! `crates/epics-base-rs/envconfig/CONFIG_BASE_VERSION`, exactly as C's
//! `makeEpicsVersion.pl` generates `epicsVersion.h` from `configure/`.
//! DO NOT EDIT — bump the spec and regenerate. `env-codegen --check` fails on
//! drift and runs as part of `cargo nextest run -p env-codegen`.
//!
//! These are the EPICS Base version, NOT the `epics-libcom-rs` crate version
//! (`CARGO_PKG_VERSION`): the crate version tracks the Rust port's own release
//! cadence, these name the upstream release being ported.

/// C `EPICS_VERSION` — the major number.
pub const EPICS_VERSION: u32 = 7;
/// C `EPICS_REVISION`.
pub const EPICS_REVISION: u32 = 0;
/// C `EPICS_MODIFICATION`.
pub const EPICS_MODIFICATION: u32 = 10;
/// C `EPICS_PATCH_LEVEL`.
pub const EPICS_PATCH_LEVEL: u32 = 1;
/// C `EPICS_DEV_SNAPSHOT` — `"-DEV"` between releases, empty on one.
pub const EPICS_DEV_SNAPSHOT: &str = "-DEV";
/// C `EPICS_SITE_VERSION` — a site's local version suffix, empty upstream.
pub const EPICS_SITE_VERSION: &str = "";

/// C `EPICS_VERSION_SHORT` — the release, with no snapshot or site suffix.
pub const EPICS_VERSION_SHORT: &str = "7.0.10.1";
/// C `EPICS_VERSION_FULL` — short version plus the snapshot and site suffixes.
pub const EPICS_VERSION_FULL: &str = "7.0.10.1-DEV";
/// C `EPICS_VERSION_STRING` — what every tool's `-V` banner prints.
pub const EPICS_VERSION_STRING: &str = "EPICS 7.0.10.1-DEV";
/// C `epicsReleaseVersion`.
pub const EPICS_RELEASE_VERSION: &str = "EPICS R7.0.10.1-DEV";
/// C `EPICS_VERSION_INT` — `VERSION_INT(V, R, M, P)`, for numeric compares.
pub const EPICS_VERSION_INT: u32 = 0x07000a01;
