//! The synApps `mca` record — a multichannel analyzer spectrum, its regions of
//! interest, and its acquisition presets.
//!
//! Ported from `mca/mcaApp/mcaSrc` (upstream `687d563`, "Remove Form Feed
//! characters"). The record's field declaration is NOT written here: it is
//! generated by `tools/dbd-codegen` from the vendored, byte-identical
//! [`mcaRecord.dbd`](../../dbd/mcaRecord.dbd) into
//! [`record::dbd_generated`], on exactly the terms every base record type's
//! table is generated, and held current by the same drift gate
//! (`dbd_codegen::tests::generated_files_are_not_stale`).
//!
//! # C reference pins
//!
//! Every `file.c:NNN` citation in this crate resolves at the tree and revision
//! below, not at whatever that tree's working copy holds today. These trees are
//! checked out on local branches here and run ahead of their pins.
//!
//! | tree | pinned revision |
//! | --- | --- |
//! | `mca` | `687d563` (tree carries no tags) |
//! | `epics-base` | `R7.0.10` |
//!
//! **Resolve by symbol at the pin; the line is a hint.** Find the named
//! function, struct, macro or field first, and treat the line number as a hint
//! that has to land inside that construct. Three cases follow:
//!
//! 1. Construct at the pin, line lands in it — the citation is exact. A
//!    reference checkout ahead of the pin will disagree; that disagreement is
//!    the checkout's, not the citation's.
//! 2. Construct at the pin, line lands outside it — line drift. Keep the
//!    symbol and move the line to the pin's.
//! 3. Construct absent at the pin — the citation means code added after it,
//!    and is NOT moved onto the pin, where it would point at lines that do not
//!    exist. It names the revision it means inline, beside the line span: the
//!    upstream PR and commit, and that both are later than the pin this table
//!    gives. `epics-libcom-rs` already carries that form.
//!
//! Every pin above passes `git merge-base --is-ancestor <pin> origin/<default>`
//! in its own tree, which is the test a pin has to meet. A `git describe`
//! string names an exact commit and is worth as much as a tag; what
//! disqualifies a revision is being reachable only from a fork branch or an
//! unmerged PR, because then it names nothing a reader outside this workspace
//! can fetch.
//!
//! Resolve each citation on its own. One sentence can cite two lines that are
//! right at different revisions, and a check run at either revision then
//! reports a single tidy error while vouching for the very citation the other
//! condemns.
//!
//! A row reading *no settled pin* means no revision has been agreed for that
//! tree: say which revision you read, and do not take its `HEAD` for the pin.
//! Citations into non-EPICS sources (libc, RTEMS, `rtems-libbsd`, VxWorks,
//! vendored third-party) are outside this table and carry no pin.

pub mod record;
pub mod soft;

pub use record::McaRecord;
pub use soft::SoftMca;

/// Path to the bundled `.dbd`.
pub const MCA_DBD_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/dbd");

/// The `mca` record type factory, for `IocBuilder::register_record_type`.
pub fn mca_record_factory() -> (&'static str, epics_base_rs::server::RecordFactory) {
    ("mca", Box::new(|| Box::new(McaRecord::default())))
}

/// Register the `mca` record type in the global registry (legacy path; prefer
/// [`mca_record_factory`] with `IocBuilder::register_record_type`).
pub fn register_mca_record_type() {
    let (name, factory) = mca_record_factory();
    epics_base_rs::server::db_loader::register_record_type(name, factory);
}
