//! The synApps `mca` record — a multichannel analyzer spectrum, its regions of
//! interest, and its acquisition presets.
//!
//! Ported from `mca/mcaApp/mcaSrc` (upstream `687d563`, "Remove Form Feed
//! characters"). The record's field declaration is NOT written here: it is
//! generated by `tools/dbd-codegen` from the vendored, byte-identical
//! [`mcaRecord.dbd`](../../dbd/mcaRecord.dbd) into
//! [`record::dbd_generated`], on exactly the terms every base record type's
//! table is generated, and held current by the same drift gate
//! (`dbd_codegen::tests::generated_files_are_not_stale`).

pub mod record;
pub mod soft;

pub use record::McaRecord;
pub use soft::SoftMca;

/// Path to the bundled `.dbd`.
pub const MCA_DBD_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/dbd");

/// The `mca` record type factory, for `IocBuilder::register_record_type`.
pub fn mca_record_factory() -> (&'static str, epics_base_rs::server::RecordFactory) {
    ("mca", Box::new(|| Box::new(McaRecord::default())))
}

/// Register the `mca` record type in the global registry (legacy path; prefer
/// [`mca_record_factory`] with `IocBuilder::register_record_type`).
pub fn register_mca_record_type() {
    let (name, factory) = mca_record_factory();
    epics_base_rs::server::db_loader::register_record_type(name, factory);
}
