//! Breakpoint tables, transcribed from the vendored `dbd/bpt*.dbd`.
//!
//! @generated by `tools/dbd-codegen` from `crates/epics-base-rs/dbd/bpt*.dbd`.
//! DO NOT EDIT. Re-run `cargo run -p dbd-codegen -- --write` after changing a
//! vendored `.dbd`; `cargo run -p dbd-codegen -- --check` fails on drift.
//!
//! These are `makeBpt`'s OUTPUT, byte-for-byte as an EPICS install ships them
//! in `dbd/`. C's `makeBpt` fits the raw sensor curve in `bpt*.data` down to a
//! handful of breakpoints; the breakpoints are the contract, and re-running the
//! fit in Rust could only move them.

/// The `(raw, eng)` points of every vendored breakpoint table, keyed by the
/// `menuConvert` / `LINR` name that selects it.
pub static BREAK_TABLES: &[(&str, &[(f64, f64)])] = &[
    // bptTypeJdegC.dbd
    (
        "typeJdegC",
        &[
            (0.0, 0.0),
            (365.023256, 67.0),
            (1000.046512, 178.0),
            (3007.255814, 524.0),
            (3543.383721, 613.0),
            (4042.988372, 692.0),
            (4101.488372, 701.0),
        ],
    ),
    // bptTypeJdegF.dbd
    (
        "typeJdegF",
        &[
            (0.0, 32.0),
            (425.209311, 161.0),
            (1218.865107, 390.0),
            (2893.652879, 869.0),
            (3603.24509, 1068.0),
            (4098.753854, 1201.0),
        ],
    ),
    // bptTypeKdegC.dbd
    (
        "typeKdegC",
        &[
            (0.0, 0.0),
            (299.2687, 74.0),
            (660.752744, 163.0),
            (1104.793671, 274.0),
            (1702.338802, 418.0),
            (2902.787322, 703.0),
            (3427.599045, 831.0),
            (3912.323051, 953.0),
            (4098.869854, 1001.0),
        ],
    ),
    // bptTypeKdegF.dbd
    (
        "typeKdegF",
        &[
            (0.0, 32.0),
            (328.639899, 178.0),
            (699.55051, 343.0),
            (1140.614626, 541.0),
            (1811.190845, 831.0),
            (2920.350505, 1305.0),
            (3472.846568, 1548.0),
            (3985.155686, 1781.0),
            (4097.083767, 1833.0),
        ],
    ),
];
