#!/usr/bin/env bash
# Build the DEPLOYABLE image for an embedded target.
#
#   scripts/embedded-image.sh rtems   ca     # realtime-ca-ioc,  armv7-rtems-eabihf
#   scripts/embedded-image.sh rtems   pva    # realtime-pva-ioc, armv7-rtems-eabihf
#   scripts/embedded-image.sh vxworks ca     # realtime-ca-ioc,  x86_64-wrs-vxworks
#   scripts/embedded-image.sh vxworks pva    # realtime-pva-ioc, x86_64-wrs-vxworks
#
# WHY THIS SCRIPT EXISTS
#
# Cargo has no target-conditional profile: nothing in a manifest can say
# "builds for these triples default to `release-embedded`". A per-target
# `rustflags` block in `.cargo/config.toml` was considered and rejected — it
# applies to every profile, so the dev/gate builds on these targets would
# inherit fat LTO (and `-C lto` + incremental is a hard rustc error). The
# default therefore lives at the only place a default CAN live: the entry
# point. This script is the single owner of the "what do we ship" invocation;
# the check gates (`rtems-check.sh`, `vxworks-check.sh`) stay
# type-check-only on the dev profile on purpose.
#
# PROFILE
#
# `release-embedded` (root `Cargo.toml`: inherits release, strip=symbols,
# lto=fat, codegen-units=1) — row 5 of the measured matrix in
# `doc/vxworks-port.md` §5.5. Override for a comparison build:
#
#   EMBEDDED_PROFILE=release scripts/embedded-image.sh vxworks ca   # row 2
#
# TOOLCHAIN / ENVIRONMENT — same operator contract as the check gates:
#
#   rtems:   `rtems-check.sh` header. The TLS spec is generated by
#            `rtems-tls-spec.sh` unless RTEMS_USE_STOCK_SPEC=1; unlike the
#            check gate this script LINKS, so `arm-rtems6-gcc` must be on
#            PATH, and the bootable-image cfg `rtems_boot_linked` is set
#            unconditionally — a deployable image without it cannot boot.
#   vxworks: `vxworks-check.sh` header — VXWORKS_TOOLCHAIN names a prepared
#            toolchain, or a stock nightly plus VXWORKS_CARGO_CONFIG carrying
#            the config-level libc patch.
#
# No `--locked`: the gates own the "this tree's committed resolution
# compiles" claim; an image build runs under whatever lock adjustment the
# target's libc route needs on the build host (see the `[patch.crates-io]`
# comment in the root manifest).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

usage() {
    echo "usage: scripts/embedded-image.sh <rtems|vxworks> <ca|pva>" >&2
    exit 2
}

OS="${1:-}"
KIND="${2:-}"
PROFILE="${EMBEDDED_PROFILE:-release-embedded}"

case "$KIND" in
    ca)  CRATE=epics-ca-rs;     BIN=realtime-ca-ioc;  FEATURES=client-core ;;
    pva) CRATE=epics-bridge-rs; BIN=realtime-pva-ioc; FEATURES=qsrv-core,pvalink ;;
    *) usage ;;
esac

# The comma in `std,panic_abort` is cargo's separator, not bash's — quoted
# for the same SC2054 reason the gates give.
ARGS=(build --profile "$PROFILE" --no-default-features
      "-Zbuild-std=std,panic_abort"
      -p "$CRATE" --bin "$BIN" --features "$FEATURES")

case "$OS" in
    rtems)
        TOOLCHAIN=nightly
        if [[ "${RTEMS_USE_STOCK_SPEC:-0}" == "1" ]]; then
            TARGET="armv7-rtems-eabihf"
        else
            TARGET="$(./scripts/rtems-tls-spec.sh)"
            ARGS+=(-Zjson-target-spec)
            # Stem = basename without .json, upper-cased, non-alnum -> _.
            _stem="$(basename "$TARGET" .json)"
            _env="CARGO_TARGET_$(printf '%s' "$_stem" | tr '[:lower:]-' '[:upper:]_')_LINKER"
            export "$_env=arm-rtems6-gcc"
        fi
        # Bootable, not portability-probe: see rtems-check.sh CONFIGS.
        export RUSTFLAGS="${RUSTFLAGS:+$RUSTFLAGS }--cfg rtems_boot_linked"
        ;;
    vxworks)
        TOOLCHAIN="${VXWORKS_TOOLCHAIN:-nightly}"
        TARGET="x86_64-wrs-vxworks"
        if [[ -n "${VXWORKS_CARGO_CONFIG:-}" ]]; then
            ARGS+=(--config "$VXWORKS_CARGO_CONFIG")
        fi
        ;;
    *) usage ;;
esac

ARGS+=(--target "$TARGET")

echo "== embedded-image: $OS $KIND ($CRATE --bin $BIN), profile $PROFILE" >&2
cargo +"$TOOLCHAIN" "${ARGS[@]}"

# Report the artifact the operator deploys. VxWorks RTPs get a `.vxe`
# extension; the RTEMS image is a bare ELF.
TARGET_DIR="${CARGO_TARGET_DIR:-target}"
STEM="$(basename "$TARGET" .json)"
for artifact in "$TARGET_DIR/$STEM/$PROFILE/$BIN.vxe" \
                "$TARGET_DIR/$STEM/$PROFILE/$BIN"; do
    if [[ -f "$artifact" ]]; then
        stat -c 'IMAGE %n %s bytes' "$artifact"
        exit 0
    fi
done
echo "embedded-image: build finished but no artifact found under $TARGET_DIR/$STEM/$PROFILE/" >&2
exit 1
