#!/usr/bin/env bash
# Build the DEPLOYABLE image for an embedded target.
#
#   scripts/embedded-image.sh rtems   ca     # realtime-ca-ioc,  armv7-rtems-eabihf
#   scripts/embedded-image.sh rtems   pva    # realtime-pva-ioc, armv7-rtems-eabihf
#   scripts/embedded-image.sh vxworks ca     # realtime-ca-ioc,  x86_64-wrs-vxworks
#   scripts/embedded-image.sh vxworks pva    # realtime-pva-ioc, x86_64-wrs-vxworks
#
# WHY THIS SCRIPT EXISTS
#
# Cargo has no target-conditional profile: nothing in a manifest can say
# "builds for these triples default to `release-embedded`". A per-target
# `rustflags` block in `.cargo/config.toml` was considered and rejected — it
# applies to every profile, so the dev/gate builds on these targets would
# inherit fat LTO (and `-C lto` + incremental is a hard rustc error). The
# default therefore lives at the only place a default CAN live: the entry
# point. This script is the single owner of the "what do we ship" invocation;
# the check gates (`rtems-check.sh`, `vxworks-check.sh`) stay
# type-check-only on the dev profile on purpose.
#
# PROFILE
#
# `release-embedded` (root `Cargo.toml`: inherits release, strip=symbols,
# lto=fat, codegen-units=1) — row 5 of the measured matrix in
# `doc/vxworks-port.md` §5.5. Override for a comparison build:
#
#   EMBEDDED_PROFILE=release scripts/embedded-image.sh vxworks ca   # row 2
#
# TOOLCHAIN / ENVIRONMENT — same operator contract as the check gates:
#
#   rtems:   `rtems-check.sh` header. The TLS spec is generated by
#            `rtems-tls-spec.sh` unless RTEMS_USE_STOCK_SPEC=1; unlike the
#            check gate this script LINKS, so `arm-rtems6-gcc` must be on
#            PATH, and the bootable-image cfg `rtems_boot_linked` is set
#            unconditionally — a deployable image without it cannot boot.
#   vxworks: `vxworks-check.sh` header — VXWORKS_TOOLCHAIN names a prepared
#            toolchain, or a stock nightly plus VXWORKS_CARGO_CONFIG carrying
#            the config-level libc patch.
#
# LIBC IN STD: unless VXWORKS_CARGO_CONFIG (or a prepared VXWORKS_TOOLCHAIN)
# supplies one, BOTH arms pass config-level libc patch lines prepared by
# `scripts/libc-std-patch.sh` from the workspace manifest's git+rev pin,
# because a manifest `[patch]` does not reach `-Zbuild-std`, and a config
# one reaches it only at the exact libc version rust-src's lock pins — the
# helper clones the pinned rev, relabels its version to match, and emits an
# ALIAS patch entry so the workspace graph keeps the committed pin while the
# std graph takes the relabelled copy (all measured; see the helper's
# header). On VxWorks std does not compile without it. On RTEMS std COMPILES
# without it but carries the stock sockaddr/time layouts, so an image built
# on a host with no ambient `~/.cargo/config.toml` patch would boot with a
# std whose address structs disagree with libbsd — the crate-graph layout
# asserts cannot see std's own libc copy. Deriving it here makes a
# deployable image's std resolution independent of build-host ambient
# config.
#
# No `--locked`: a config-added patch entry needs a lock bookkeeping write,
# which `--locked` refuses outright (measured; helper header). When the
# derived patch is in play `Cargo.lock` is snapshotted and restored on exit,
# so the tree is left as found; the gates own the "this tree's committed
# resolution compiles" claim.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

usage() {
    echo "usage: scripts/embedded-image.sh <rtems|vxworks> <ca|pva>" >&2
    exit 2
}

OS="${1:-}"
KIND="${2:-}"
PROFILE="${EMBEDDED_PROFILE:-release-embedded}"

case "$KIND" in
    ca)  CRATE=epics-ca-rs;     BIN=realtime-ca-ioc;  FEATURES=client-core ;;
    pva) CRATE=epics-bridge-rs; BIN=realtime-pva-ioc; FEATURES=qsrv-core,pvalink ;;
    *) usage ;;
esac

# The comma in `std,panic_abort` is cargo's separator, not bash's — quoted
# for the same SC2054 reason the gates give.
ARGS=(build --profile "$PROFILE" --no-default-features
      "-Zbuild-std=std,panic_abort"
      -p "$CRATE" --bin "$BIN" --features "$FEATURES")

# Append the derived libc patch (one `--config` per helper line) and arm the
# Cargo.lock snapshot/restore trap — the config-added entry writes lock
# bookkeeping (see the header's "No --locked" note).
apply_derived_libc_patch() {
    local _cfg_line _cfg_lines
    # Command substitution so a failing helper aborts the build under
    # `set -e` instead of silently building against stock libc.
    _cfg_lines=$(./scripts/libc-std-patch.sh "$1")
    [[ -n "$_cfg_lines" ]] || { echo "embedded-image: libc-std-patch.sh printed no patch lines" >&2; exit 1; }
    while IFS= read -r _cfg_line; do
        ARGS+=(--config "$_cfg_line")
    done <<<"$_cfg_lines"
    LOCK_SNAPSHOT=$(mktemp)
    cp "$REPO_ROOT/Cargo.lock" "$LOCK_SNAPSHOT"
    trap 'cp "$LOCK_SNAPSHOT" "$REPO_ROOT/Cargo.lock"; rm -f "$LOCK_SNAPSHOT"' EXIT
}

case "$OS" in
    rtems)
        TOOLCHAIN=nightly
        if [[ "${RTEMS_USE_STOCK_SPEC:-0}" == "1" ]]; then
            TARGET="armv7-rtems-eabihf"
        else
            TARGET="$(./scripts/rtems-tls-spec.sh)"
            ARGS+=(-Zjson-target-spec)
            # Stem = basename without .json, upper-cased, non-alnum -> _.
            _stem="$(basename "$TARGET" .json)"
            _env="CARGO_TARGET_$(printf '%s' "$_stem" | tr '[:lower:]-' '[:upper:]_')_LINKER"
            export "$_env=arm-rtems6-gcc"
        fi
        # Bootable, not portability-probe: see rtems-check.sh CONFIGS.
        export RUSTFLAGS="${RUSTFLAGS:+$RUSTFLAGS }--cfg rtems_boot_linked"
        apply_derived_libc_patch "$TOOLCHAIN"
        ;;
    vxworks)
        TOOLCHAIN="${VXWORKS_TOOLCHAIN:-nightly}"
        TARGET="x86_64-wrs-vxworks"
        if [[ -n "${VXWORKS_CARGO_CONFIG:-}" ]]; then
            ARGS+=(--config "$VXWORKS_CARGO_CONFIG")
        elif [[ "$TOOLCHAIN" == nightly ]]; then
            # A prepared VXWORKS_TOOLCHAIN bundles its own fixed rust-src and
            # needs no patch; the stock nightly does.
            apply_derived_libc_patch "$TOOLCHAIN"
        fi
        ;;
    *) usage ;;
esac

ARGS+=(--target "$TARGET")

echo "== embedded-image: $OS $KIND ($CRATE --bin $BIN), profile $PROFILE" >&2
cargo +"$TOOLCHAIN" "${ARGS[@]}"

# Report the artifact the operator deploys. VxWorks RTPs get a `.vxe`
# extension; the RTEMS image is a bare ELF.
TARGET_DIR="${CARGO_TARGET_DIR:-target}"
STEM="$(basename "$TARGET" .json)"
for artifact in "$TARGET_DIR/$STEM/$PROFILE/$BIN.vxe" \
                "$TARGET_DIR/$STEM/$PROFILE/$BIN"; do
    if [[ -f "$artifact" ]]; then
        stat -c 'IMAGE %n %s bytes' "$artifact"
        exit 0
    fi
done
echo "embedded-image: build finished but no artifact found under $TARGET_DIR/$STEM/$PROFILE/" >&2
exit 1
