//! UI-25 — pvxs#200's same-host / same-process discovery, run here.
//!
//! pvxs#200 ("PV generated by qsrv2 cannot be accessed from pvxs get on
//! the same IOC"): a pvxs client and QSRV2 inside ONE IOC process, where
//! the client times out on a PV that same process serves, while a client
//! in a DIFFERENT process on the same host reaches it. The reporter's
//! environment is the whole of the configuration (pvxs 1.5.2, Base
//! 7.0.10.1-DEV, Debian 12, one physical NIC plus Docker-generated
//! addresses):
//!
//! ```text
//! EPICS_PVA_ADDR_LIST=172.17.255.255 172.18.23.255
//! EPICS_PVA_AUTO_ADDR_LIST=NO
//! EPICS_PVA_BROADCAST_PORT=5076
//! EPICS_PVA_CONN_TMO=30
//! EPICS_PVAS_AUTO_BEACON_ADDR_LIST=NO
//! EPICS_PVAS_BEACON_ADDR_LIST=172.17.255.255 172.18.23.255
//! ```
//!
//! What that config *is*, stripped of the site's subnet numbers:
//! `AUTO_ADDR_LIST=NO` together with an address list holding nothing but
//! **interface broadcast** addresses — no `127.0.0.1`, no unicast host
//! address. Every SEARCH therefore leaves on a broadcast destination, and
//! a server in the searching process can only be found if that broadcast
//! comes back to it. The row is filed SUSPECTED because our port lacks
//! the suspected upstream hazard structurally (the client keeps its own
//! ephemeral SEARCH socket, separate from the server's responder; the
//! beacon listener on the shared broadcast port is best-effort and its
//! loss does not disable search) — but no such run was ever made here,
//! and a reading does not close it.
//!
//! Three deviations from the literal environment, each recorded with why
//! it cannot move the outcome:
//!
//! 1. The two literal addresses are replaced by *this* host's own
//!    `IFF_BROADCAST` interface broadcast addresses. Hard-coding another
//!    site's subnets would send the SEARCH nowhere. On the measurement
//!    host that enumeration includes `172.17.255.255` and
//!    `172.18.255.255` — the Docker-bridge broadcasts the reporter names.
//! 2. The broadcast port and the server TCP port are picked free at run
//!    time instead of 5076/5075. The reporter's values are just the
//!    protocol defaults; what the issue turns on is that client and
//!    server agree on ONE broadcast port and contend for it inside one
//!    process, which a picked port reproduces exactly. Pinning 5076 would
//!    additionally cross-talk with any other PVA process on the host and
//!    make the reading unattributable rather than more faithful.
//! 3. `EPICS_PVA_CONN_TMO=30` is set as the reporter has it, but each
//!    assertion carries its own shorter deadline, so a reproduction is a
//!    reported timeout instead of a 30 s hang.
//!
//! Two measurements, the reported case and the reporter's own control:
//! same process, and same host in a second process.
// `tokio_backend` is the gate because it is the predicate the UDP items this
// test names carry, and because it excludes the RTEMS target as well as the
// host exec backend — that target can run neither measurement.
#![cfg(tokio_backend)]
#![cfg(feature = "client")]

use std::net::{Ipv4Addr, UdpSocket};
use std::process::Command;
use std::sync::Arc;
use std::time::Duration;

use epics_base_rs::net::iface_v4::{IfaceV4, enumerate};
use epics_pva_rs::client_native::context::PvaClient;
use epics_pva_rs::nt::typed::TypedNT;
use epics_pva_rs::pvdata::{PvField, ScalarValue};
use epics_pva_rs::server_native::{PvaServer, PvaServerConfig, SharedPV, SharedSource};
use serial_test::serial;

/// The value the served PV holds, so a wrong-server answer is visible as a
/// wrong number rather than as a pass.
const VALUE: f64 = 25.0;

/// The environment pvxs#200 reports, with this host's broadcast addresses
/// and a picked port pair. Returns the address list actually used so the
/// test can print what it measured.
///
/// # Safety (edition 2024)
///
/// Process-env writes; the two tests in this file are `#[serial]`, so no
/// other thread reads or writes the environment concurrently.
fn apply_pvxs200_env(udp_port: u16) -> String {
    // `broadcast_addrs()` is deliberately NOT used: it is C's SEARCH
    // destination set, which for a point-to-point interface is the PEER
    // address — and on a `wg`/tailscale `/32` that peer address is the
    // host's own unicast address. One such entry would let the SEARCH
    // reach the same-process server by plain loopback delivery and the
    // measurement would report success without ever testing the
    // broadcast-only configuration the issue describes. Keep only
    // `IFF_BROADCAST` interfaces and take their broadcast address.
    let ifaces: Vec<IfaceV4> = enumerate().expect("enumerate interfaces");
    let mut dests: Vec<std::net::Ipv4Addr> = Vec::new();
    for i in &ifaces {
        if i.is_eligible()
            && i.is_broadcast()
            && let Some(b) = i.dest.filter(|b| !b.is_unspecified())
            && !dests.contains(&b)
        {
            dests.push(b);
        }
    }
    // The property the reporter's list has, asserted rather than assumed:
    // no entry is an address of this host.
    for d in &dests {
        assert!(
            !ifaces.iter().any(|i| i.ip == *d),
            "{d} is one of this host's own addresses; a unicast entry would \
             make the same-process SEARCH a loopback delivery and void the \
             measurement"
        );
    }
    let addr_list = dests
        .iter()
        .map(|a| a.to_string())
        .collect::<Vec<_>>()
        .join(" ");
    // Not an early return: a host with no broadcast-capable NIC cannot
    // carry this configuration at all, and nextest scores an early return
    // as a pass. Fail loudly instead.
    assert!(
        !addr_list.is_empty(),
        "pvxs#200's configuration is an all-broadcast EPICS_PVA_ADDR_LIST; \
         this host enumerates no broadcast-capable interface, so the run \
         cannot be made here"
    );
    unsafe {
        std::env::set_var("EPICS_PVA_ADDR_LIST", &addr_list);
        std::env::set_var("EPICS_PVA_AUTO_ADDR_LIST", "NO");
        std::env::set_var("EPICS_PVA_BROADCAST_PORT", udp_port.to_string());
        std::env::set_var("EPICS_PVA_CONN_TMO", "30");
        std::env::set_var("EPICS_PVAS_AUTO_BEACON_ADDR_LIST", "NO");
        std::env::set_var("EPICS_PVAS_BEACON_ADDR_LIST", &addr_list);
        // Not in the reporter's list: deviation 2. The server reads its TCP
        // bind port from here, and `0` is the kernel's "pick one" — the
        // number is then whatever the listener that actually came up holds,
        // published by [`name_the_bound_tcp_port`] before any client is
        // built.
        std::env::set_var("EPICS_PVA_SERVER_PORT", "0");
    }
    addr_list
}

fn clear_pvxs200_env() {
    unsafe {
        for k in [
            "EPICS_PVA_ADDR_LIST",
            "EPICS_PVA_AUTO_ADDR_LIST",
            "EPICS_PVA_BROADCAST_PORT",
            "EPICS_PVA_CONN_TMO",
            "EPICS_PVAS_AUTO_BEACON_ADDR_LIST",
            "EPICS_PVAS_BEACON_ADDR_LIST",
            "EPICS_PVA_SERVER_PORT",
        ] {
            std::env::remove_var(k);
        }
    }
}

/// The one port in this test that still has to be named before anything
/// binds: a SEARCH is sent to a port both halves agreed on in advance, so
/// neither the client nor the server can be the one that picks it.
///
/// That leaves the pick-and-drop window here and nowhere else in this file.
/// The server's TCP port used to be picked the same way and no longer is —
/// see [`name_the_bound_tcp_port`], which reads the number off the listener
/// that came up instead of predicting it.
fn pick_broadcast_port() -> u16 {
    let u = UdpSocket::bind((Ipv4Addr::UNSPECIFIED, 0)).expect("pick udp port");
    let port = u.local_addr().unwrap().port();
    drop(u);
    port
}

/// Publish the TCP port the server actually bound, so a client built after
/// this reads a number somebody owns rather than one somebody guessed.
///
/// `EPICS_PVA_SERVER_PORT` went into the environment as `0` before the
/// server started; the server turned that into a bound listener, and this is
/// where the answer comes back out.
fn name_the_bound_tcp_port(server: &PvaServer) -> u16 {
    let port = server.tcp_addr().port();
    // SAFETY: same as `apply_pvxs200_env` — both tests here are `#[serial]`
    // and no thread of theirs reads the environment concurrently.
    unsafe {
        std::env::set_var("EPICS_PVA_SERVER_PORT", port.to_string());
    }
    port
}

/// The server half: a wildcard-bound PVA server carrying the env config,
/// hosting one NTScalar. This is the `qsrv2` of the issue.
fn serve(pv_name: &str) -> PvaServer {
    let pv = SharedPV::new();
    pv.open(f64::descriptor(), f64::to_pv_field(&VALUE))
        .expect("open shared pv");
    let source = SharedSource::new();
    source.add(pv_name, pv);
    let config = PvaServerConfig::default().with_env();
    PvaServer::start(Arc::new(source), config).expect("PVA server must start")
}

fn scalar_f64(v: &PvField) -> f64 {
    match v {
        PvField::Scalar(ScalarValue::Double(d)) => *d,
        PvField::Structure(s) => s
            .fields
            .iter()
            .find(|(n, _)| n == "value")
            .map(|(_, f)| scalar_f64(f))
            .unwrap_or_else(|| panic!("no `value` leaf in {v:?}")),
        other => panic!("not an NTScalar double: {other:?}"),
    }
}

/// The reported case: client and server in ONE process, discovering each
/// other through UDP SEARCH under pvxs#200's environment.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
#[serial]
async fn same_process_client_reaches_a_same_process_server_under_pvxs200_env() {
    let udp_port = pick_broadcast_port();
    let addr_list = apply_pvxs200_env(udp_port);
    let pv_name = "UI25:SAMEPROC";
    let server = serve(pv_name);
    let tcp_port = name_the_bound_tcp_port(&server);

    // Built after the env is in place: the client resolves its search
    // config once, at build time (`ClientSearchConfig::from_env`).
    let client = PvaClient::new().expect("client");
    let got = tokio::time::timeout(Duration::from_secs(10), client.pvget(pv_name)).await;

    let outcome = match &got {
        Err(_) => "TIMED OUT after 10s (pvxs#200 reproduced)".to_string(),
        Ok(Err(e)) => format!("FAILED: {e} (pvxs#200 reproduced)"),
        Ok(Ok(v)) => format!("resolved, value = {}", scalar_f64(v)),
    };
    println!(
        "UI-25 same-process: EPICS_PVA_ADDR_LIST=\"{addr_list}\" \
         EPICS_PVA_AUTO_ADDR_LIST=NO EPICS_PVA_BROADCAST_PORT={udp_port} \
         EPICS_PVA_SERVER_PORT={tcp_port} -> {outcome}"
    );

    let value = got
        .expect(
            "pvxs#200 reproduced: a SEARCH for a PV this same process serves \
             found no server within 10s under the issue's environment",
        )
        .expect("pvxs#200 reproduced: the same-process GET failed");
    assert_eq!(scalar_f64(&value), VALUE);
    drop(server);
    clear_pvxs200_env();
}

/// The reporter's own control: the identical server, reached by a client
/// in a SECOND process on the same host. pvxs#200 says this case works
/// where the same-process one does not, so measuring only the first would
/// leave a failure unattributable to same-process-ness.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
#[serial]
async fn same_host_other_process_client_reaches_the_server_under_pvxs200_env() {
    let udp_port = pick_broadcast_port();
    let addr_list = apply_pvxs200_env(udp_port);
    let pv_name = "UI25:OTHERPROC";
    let server = serve(pv_name);
    let tcp_port = name_the_bound_tcp_port(&server);

    // `env!`, not `option_env!`: `pvget-rs` is a `[[bin]]` of this package
    // under the `client` feature this test target already builds with, so
    // an absent path is a broken build, not an unmet prerequisite.
    let out = Command::new(env!("CARGO_BIN_EXE_pvget-rs"))
        .arg(pv_name)
        .env("EPICS_PVA_ADDR_LIST", &addr_list)
        .env("EPICS_PVA_AUTO_ADDR_LIST", "NO")
        .env("EPICS_PVA_BROADCAST_PORT", udp_port.to_string())
        .env("EPICS_PVA_CONN_TMO", "30")
        .env("EPICS_PVA_SERVER_PORT", tcp_port.to_string())
        .output()
        .expect("spawn pvget-rs");
    let stdout = String::from_utf8_lossy(&out.stdout).to_string();
    let stderr = String::from_utf8_lossy(&out.stderr).to_string();
    println!(
        "UI-25 other-process: pvget-rs {pv_name} -> status={:?}\nstdout: {stdout}\nstderr: {stderr}",
        out.status.code()
    );

    assert!(
        out.status.success(),
        "the reporter's working control failed here: a second process on \
         the same host could not reach the server under pvxs#200's \
         environment (status={:?}, stderr: {stderr})",
        out.status.code()
    );
    assert!(
        stdout.contains("25"),
        "pvget-rs reached a server but not this one (expected the value \
         {VALUE}); stdout: {stdout}"
    );
    drop(server);
    clear_pvxs200_env();
}
